apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: web-app
    template:
        matadata:
            labels:
                app: web-app
        spec:
            containers:
            - name: web-app
              image: ngnix:1.25
              pors:
                - containerPort: 80