apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: dev-environment
spec:
  containers:
  - name: debug-pod
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_MODE
      