apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dev-environment
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000


# 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-Ingress
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
