apiVersion: v1
kind: StatefulSet
metadata:
  name: db
  namespace: dev-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
    - name: db
      image: postgres:16
      ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER:
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: POSTGRES_PASSWORD