apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: dev-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
     containers:
      - name: web-app
        image: nginx:1.25
        ports:
        - containerPort: 80
        