apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: dev-environment
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
