apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-api
    specs:
      containers:
        - name: web-app
          image: nginx:1.25
          ports:
          - containerPort: 80