apiVersion: v1
kind: Service
metadata:
  name: math-service
spec:
  type: ClusterIP
  selector:
    app: math-service
  ports:
    - protocol: TCP
      port: 80          # Puerto interno del servicio (puerto lógico dentro de Kubernetes)
      targetPort: 3001  # Puerto donde escucha tu app dentro del contenedor
