apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
        - name: myapp
          image: 
          ports:
          - containerPort: 80
