---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgDDE8ANv2JKTVuv1ZiugU7PO11CSkp1B/skhsIbWherxU7Si95m5626O7iYRiIhvJ/e5/tDLSF38wDdHbRB3PlwmgxZCQ+EMUfGpPsehP1BeEnwUiLY8NHm5/KCThcihSraob63n8LMfzzmkbs/NEd7a/bEU+dr/4JmtFA86MwsCWwM+Wr1Xs+Ojm45Qn4S6381Ip5rFsUmScnC8rJgng7gXTrzwRfL9EzPx1AUH71YwHFM53GpP3P0/boD81l423/ci5JxRpEvEG3Arhi4QeMSpvAxCFx6XvmPLtLYLovgnNrxFQxiyuF8HjfWFCOhxvLBLIU4TKyriaY0VlrOk74dePY7dN1uWF+HTX8lwqd7Ix0EOdlqr0lmsTNhtRGJVSkaFxeaub1kK7insksUFV6AhcU/WJRRHQQzZxgGAoUg7jnoKh26LEdS+dXiJ0KdBvvD7v/aTg5HGNADNXVscMGASHtvgNey4KKddHd236IlK8i+7pNpIdP+xyJIa94nv6WKr+ov5iIX2drInpgvOlxkJ6WTFMWYuX4UkPQoo7GQtk7d8rokYcxKjBkJbNnvrdSC+sYb2EDVEVvSi8sRwSDXz/5FPOMI0CLQqfADPZ3v6zb73bzyd4smDacALQaJCFaw6/Af8TTjRxD0qJg5oUt/eD8AWkU179v8mT0pqlx4JIc54irXtOFmk6PzL5QbBlTMtywtIAXTZzA=
    username: AgBOkxPiyTuONzXN02OIpaBQwNXbhAbJ14OsUoJiuTDqk0eFMCEusKQJBM8T6qwDdnuqNbHSrRoRudQwEi4GlzRnmFMHQ5ygU87dxuJ1KSAEsbsJgVJNQjb95x4qQuM+pS4BwqWHeXU28ha3AZQ9nRO/JTNprcQvZs0I9jaly7paUScC0IIR82f1YWhKlSvWHyKeexFN7kpIYwPDr75oyBbmpuYzLHcE+WKEkwgph+V8lzQRdV9fb78GNlnECpZ3uW1SBZsxYA8HN5uiLc+G290bDPBTcVilL/dx13ukXhfXC7pWiJqRujsGyC0nV+wUkEFgKgyFvfj9O/sIIwWnLGJl+Mi92KKwc5BSILDUMu4dzOzAKzICJMfbL4Js33DFcCDHidD1/nSIdTHDFQDQZZfL5TSFzqbP4q4q+4rwUrEVg+V6VlQV1LS2lLUeiUpLe25KO36yS4pS1H4jWwJzL3Ewlz7hHy4H+Mq6Rn+PsKtsrZMM36p3aVAOMTQZAmoLXTvYz6ezA6z758pw/Z7doCbPVvNDkOhy9QZec+Sbgwm/tMqQ4MdE2WUISnda49XqTBk5YpU2NMdzLnRDt0xdMYgR11XWr2RAJ3jGLQW1lqoSGPB4lkoo4cwNJPQPEripsE+9S4goz9p898jCHoWjoY5NYlGCDPaV0vOcoUI49ONgeUfFLuCyYkdwg1gthZqrornFQry4vI3slY0=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
